### ISSUE TITLE
Blind Tilt Update?

### ISSUE THREAD

**Issue by jianyu-li** [tomwpublic/hubitat_switchbot#22]
It looks like the API has been updated to include the new blind tilt. Is that something that can be added? [Github](https://github.com/OpenWonderLabs/SwitchBotAPI#blind-tilt)

**Comment by jianyu-li** [comment]
i cobbled together an update that gives me the status and i can open and close the blinds using the curtain driver as a base. unfortunately i don't know this very well but if you need any of the info i found out so far let me know

**Comment by tomwpublic** [comment]
> Is that something that can be added?

Thank you for letting me know.  I have an implementation that uses the new API.  Please contact me via the Hubitat forums if you would like to test it out.

**Comment by jianyu-li** [comment]
Thanks for updating!

**Comment by tomwpublic** [comment]
https://github.com/tomwpublic/hubitat_switchbot/commit/f0df96defeb4cf555b17759079c6c832647b4488
