### ISSUE TITLE
Typo in Blind Tilt

### ISSUE THREAD

**Issue by ccoupe** [tomwpublic/hubitat_switchbot#24]
I was reading the code (nicely done, BTW) and found what I think is a typo that very few would find in real life usage.  Too small for a pull request. 
In SwitchbotBlindTilt, line 36 in the command description is 
`description:"Desired tile direction"`
I'm guessing that should be 'tilt' not 'tile'

**Comment by tomwpublic** [comment]
Good catch!

https://github.com/tomwpublic/hubitat_switchbot/commit/4f25a685ae23a9615590cae6b0c5d228e1119928
