### ISSUE TITLE
SwitchBot IR Device's current state always on

### ISSUE THREAD

**Issue by oceancyt0922** [tomwpublic/hubitat_switchbot#4]
Hi, I found that the current state of my IR device (aircon) always remain "on" even I switched off the aircon.

**Comment by tomwpublic** [comment]
Can you clarify which state you are referring to?  Is this a state that is reported in Hubitat, or do you mean that even if you issue the Off command in Hubitat it does not affect the aircon?  Does it work from the SwithBot app?

**Comment by oceancyt0922** [comment]
> Can you clarify which state you are referring to? Is this a state that is reported in Hubitat, or do you mean that even if you issue the Off command in Hubitat it does not affect the aircon? Does it work from the SwithBot app?

**Comment by oceancyt0922** [comment]
My aircon can be switched off when I issue the off command in both SwitchBot app and HE.  But, the current state in HE remain "on" such that my homekit dashboard showed the aircon is "on" even it's actually switched off.

**Comment by tomwpublic** [comment]
Ok, I understand.

Unfortunately there is no way to query the on/off status of an IR device because it is a stateless operation from the SwitchBot system.

I would encourage you to find another way to reflect the status of the aircon device.
